<?php

namespace App\Models;

use Grimzy\LaravelMysqlSpatial\Eloquent\SpatialTrait;
use Grimzy\LaravelMysqlSpatial\Types\Point;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Investment extends Model
{
    use HasFactory;
    use SpatialTrait;

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function($model) {
            $model->user_id = auth()->id() ?? User::all()->random()->id;
        });
    }

    protected $fillable = [
        'commodity_id',
        'title',
        'intervention_id',
        'description',
        'quantity',
        'cost',
        'location_map',
        'proponent',
        'beneficiaries',
        'justification',
        'user_id',
    ];

    protected $spatialFields = [
        'location_map',
    ];

    public function intervention(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(Intervention::class);
    }

    public function province()
    {

    }
}
